var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/share/[shareId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j~rhrf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0sdw-up.js")
R.c("server/chunks/ssr/_083t~gs._.js")
R.c("server/chunks/ssr/_0pvy5k.._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qre.e5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_share_[shareId]_page_actions_0zruu.o.js")
R.m(11308)
module.exports=R.m(11308).exports
