var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/report/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jz9084._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0wr5kf1.js")
R.c("server/chunks/ssr/_0pvy5k.._.js")
R.c("server/chunks/ssr/_083t~gs._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qre.e5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_0cj5b.g._.js")
R.c("server/chunks/ssr/_next-internal_server_app_report_[id]_page_actions_08ej_y0.js")
R.m(83853)
module.exports=R.m(83853).exports
